spring:
  datasource:
    url: jdbc:mysql://192.168.101.122:3306/warehouse?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: hive
    password: admin
    driver-class-name: com.mysql.jdbc.Driver